import { NextResponse } from "next/server";

// Centralized API error codes — language-neutral.
// The client translates these via i18n keys: `api_error_${code}` (lowercase).

export const API_ERRORS = {
  // Generic
  INVALID_ID: "INVALID_ID",
  INVALID_DATE: "INVALID_DATE",
  INVALID_DATE_FORMAT: "INVALID_DATE_FORMAT",

  // Auth
  PIN_REQUIRED: "PIN_REQUIRED",
  PIN_INVALID_FORMAT: "PIN_INVALID_FORMAT",
  PIN_WRONG: "PIN_WRONG",
  PIN_ALREADY_USED: "PIN_ALREADY_USED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  NURSE_PIN_MUST_BE_4: "NURSE_PIN_MUST_BE_4",
  MANAGER_PIN_MUST_BE_6: "MANAGER_PIN_MUST_BE_6",

  // Users
  USER_NOT_FOUND: "USER_NOT_FOUND",
  CANNOT_DEACTIVATE_MANAGER: "CANNOT_DEACTIVATE_MANAGER",

  // Nurses
  NURSE_NOT_FOUND: "NURSE_NOT_FOUND",
  NURSE_NOT_FOUND_OR_INACTIVE: "NURSE_NOT_FOUND_OR_INACTIVE",
  SOME_NURSES_NOT_FOUND: "SOME_NURSES_NOT_FOUND",

  // Clinics
  CLINIC_NOT_FOUND: "CLINIC_NOT_FOUND",
  CLINIC_CODE_EXISTS: "CLINIC_CODE_EXISTS",
  SOME_CLINICS_NOT_FOUND: "SOME_CLINICS_NOT_FOUND",

  // Monthly dates
  MONTHLY_DATE_NOT_FOUND: "MONTHLY_DATE_NOT_FOUND",

  // Fixed assignments
  FIXED_ASSIGNMENT_NOT_FOUND: "FIXED_ASSIGNMENT_NOT_FOUND",
  FIXED_ASSIGNMENT_DUPLICATE: "FIXED_ASSIGNMENT_DUPLICATE",

  // Schedule
  SCHEDULE_NOT_FOUND: "SCHEDULE_NOT_FOUND",
  ASSIGNMENT_NOT_FOUND: "ASSIGNMENT_NOT_FOUND",
  NURSE_PROFILE_NOT_FOUND: "NURSE_PROFILE_NOT_FOUND",
  DUPLICATE_DAY_IN_REQUEST: "DUPLICATE_DAY_IN_REQUEST",
  HOURS_EXCEED_CONTRACT: "HOURS_EXCEED_CONTRACT",

  // Programs
  PROGRAM_NOT_FOUND: "PROGRAM_NOT_FOUND",

  // Requests
  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  START_DATE_MUST_BE_FUTURE: "START_DATE_MUST_BE_FUTURE",
  END_DATE_AFTER_START: "END_DATE_AFTER_START",
  OFF_DAY_SINGLE_DAY_ONLY: "OFF_DAY_SINGLE_DAY_ONLY",
  DUPLICATE_PENDING_REQUEST: "DUPLICATE_PENDING_REQUEST",

  // Tasks
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_NOT_AUTHORIZED: "TASK_NOT_AUTHORIZED",
  TASK_MUST_ASSIGN_OR_ALL: "TASK_MUST_ASSIGN_OR_ALL",

  // Announcements
  ANNOUNCEMENT_NOT_FOUND: "ANNOUNCEMENT_NOT_FOUND",
  ANNOUNCEMENT_NOT_AUTHORIZED: "ANNOUNCEMENT_NOT_AUTHORIZED",

  // Notifications
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",

  // Reports
  MISSING_MONTH_PARAM: "MISSING_MONTH_PARAM",
} as const;

export type ApiErrorCode = (typeof API_ERRORS)[keyof typeof API_ERRORS];

export function apiError(
  code: ApiErrorCode,
  status: number,
  detail?: Record<string, unknown>,
) {
  return NextResponse.json({ error: code, ...detail }, { status });
}
